[project]
name = "Doublet Quantifier"
version = "0.0.1"

[owner]
name = "Alexandra Baldelli"
# tools
[tool.black]
line-length = 88
target-version = ["py310", "py311", "py312"]

[tool.ruff]
line-length = 88
target-version = "py311"